// try...catch..finally

var a = 10;
var b = 20;

try {
  console.log(a + b);
  console.log(c);
} catch (error) {
  console.log(`Error is : ${error}`);
} finally {
  console.log("I Continue AnyHow the Code is ");
}
